# Generated by Django 4.1.7 on 2023-03-26 14:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nomeGuerra', models.CharField(max_length=60, unique=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('om', models.CharField(blank=True, max_length=50)),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('grau_hieq', models.CharField(max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EfetivoVariavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeGuerra', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('om', models.CharField(blank=True, max_length=50)),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('tipoSanguineo', models.CharField(blank=True, max_length=3)),
                ('grau_hieq', models.CharField(blank=True, default='SD', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'efetivo variavel',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='core.efetivovariavel')),
            ],
        ),
        migrations.CreateModel(
            name='FatoObservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=8)),
                ('motivo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField(blank=True, default='2023-03-26', null=True)),
                ('aplicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fos', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fo', to='core.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='FATD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punicao', models.CharField(choices=[('Advertência', 'Advertência'), ('Repreensão', 'Repreensão'), ('Detenção', 'Detenção'), ('Prisão', 'Prisão'), ('Exclusão a bem da disciplina', 'Exclusão a bem da disciplina')], max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField(blank=True, default='2023-03-26', null=True)),
                ('aplicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatds', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatd', to='core.ficha')),
            ],
        ),
    ]
