# Generated by Django 4.1.7 on 2023-03-25 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfetivoVariavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeGuerra', models.CharField(max_length=60)),
                ('numero', models.IntegerField()),
                ('nomeCompleto', models.CharField(max_length=200)),
                ('cpf', models.CharField(blank=True, max_length=11)),
                ('tipoSanguineo', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'verbose_name_plural': 'efetivo variavel',
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='core.efetivovariavel')),
            ],
        ),
        migrations.CreateModel(
            name='FatoObservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fator', models.CharField(choices=[(1, 'Positivo'), (2, 'Negativo')], max_length=8)),
                ('motivo', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=200)),
                ('ficha', models.ManyToManyField(related_name='fo', to='core.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='FATD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punicao', models.CharField(choices=[(1, 'Advertência'), (2, 'Repreensão'), (3, 'Detenção'), (4, 'Prisão'), (5, 'Exclusão a bem da disciplina')], max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('ficha', models.ManyToManyField(related_name='fatd', to='core.ficha')),
            ],
        ),
    ]
