# Generated by Django 4.1.7 on 2023-04-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efetivovariavel',
            name='foto',
            field=models.FileField(blank=True, upload_to='efetivovariavel'),
        ),
        migrations.AlterField(
            model_name='fatd',
            name='data',
            field=models.DateField(blank=True, default='2023-04-07', null=True),
        ),
        migrations.AlterField(
            model_name='fatoobservado',
            name='data',
            field=models.DateField(blank=True, default='2023-04-07', null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ev',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='core.efetivovariavel'),
        ),
    ]
