# Generated by Django 4.1.7 on 2023-03-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatd',
            name='data',
            field=models.DateField(blank=True, default='2023-03-25', null=True),
        ),
        migrations.AddField(
            model_name='fatoobservado',
            name='data',
            field=models.DateField(blank=True, default='2023-03-25', null=True),
        ),
        migrations.AlterField(
            model_name='fatd',
            name='punicao',
            field=models.CharField(choices=[('Advertência', 'Advertência'), ('Repreensão', 'Repreensão'), ('Detenção', 'Detenção'), ('Prisão', 'Prisão'), ('Exclusão a bem da disciplina', 'Exclusão a bem da disciplina')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fatoobservado',
            name='fator',
            field=models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=8),
        ),
    ]
