# Generated by Django 4.1.7 on 2023-04-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_efetivovariavel_foto_alter_fatd_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efetivovariavel',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='efetivovariavel'),
        ),
        migrations.AlterField(
            model_name='fatd',
            name='data',
            field=models.DateField(blank=True, default='2023-04-09', null=True),
        ),
        migrations.AlterField(
            model_name='fatoobservado',
            name='data',
            field=models.DateField(blank=True, default='2023-04-09', null=True),
        ),
    ]
